### ISSUE TITLE
Error when running opengb init

### ISSUE THREAD

**Issue by denishacquin** [rivet-gg/opengb#329]
Hey, I am having the following error when running `opengb init`:

`error: Uncaught (in promise) TypeError: Must be a file URL.
    throw new TypeError("Must be a file URL.");
          ^
    at assertArg (https://deno.land/std@0.208.0/path/_common/from_file_url.ts:7:11)
    at fromFileUrl (https://deno.land/std@0.208.0/path/posix/from_file_url.ts:17:9)
    at fromFileUrl (https://deno.land/std@0.208.0/path/from_file_url.ts:25:48)
    at https://raw.githubusercontent.com/rivet-gg/opengb/main/src/build/entrypoint.ts:10:62`
    
I have installed Deno, docker and git and I'm on MacOs.

Any ideas?

**Comment by NathanFlurry** [comment]
hey @denishacquin! apologies, this issue missed my inbox.

can you try installing the latest version again:

```
deno install -n opengb -fgA https://raw.githubusercontent.com/rivet-gg/opengb/v0.1.5/src/cli/main.ts
```
