### ISSUE TITLE
Prisma leaks timeout in test

### ISSUE THREAD

**Issue by NathanFlurry** [rivet-gg/opengb#35]
Run a test with `deno test --trace-ops` and disable `sanitizeOps` in `Runtime.test` to see the issue:

```
    at op_sleep (ext:core/00_infra.js:265:13)
    at runAfterTimeout (ext:deno_web/02_timers.js:234:20)
    at initializeTimer (ext:deno_web/02_timers.js:192:3)
    at setTimeout (ext:deno_web/02_timers.js:336:10)
    at pm (file:///Users/nathan/rivet/ogs/dist/prisma/friends/esm.js:7264:14)
    at <anonymous> (wasm://wasm/00952342:1:2131297)
    at <anonymous> (wasm://wasm/00952342:1:2153871)
    at am (file:///Users/nathan/rivet/ogs/dist/prisma/friends/esm.js:7183:9)
    at n (file:///Users/nathan/rivet/ogs/dist/prisma/friends/esm.js:7252:20)
    at new Promise (<anonymous>)
```

Sanitize ops is disabled until this can be fixed.

**Comment by NathanFlurry** [comment]
No longer an issue now that we use docker for this
